[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@10.4.1 --activate",
  "pnpm install"
]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "node dist/index.js"